IMAGE_TITLE = "Popeye"
APP_NAME = "World of Warcraft"
APP_WIDTH = 1280
APP_HEIGHT = 800

WIDTH_FIX = 10
APP_TITLEBAR_HEIGHT = 50

RESIZE_WIDTH = int(APP_WIDTH / 1.49)
RESIZE_HEIGHT = int(APP_HEIGHT / 1.48)
